Bd 1768 add explode function to transform block
husqvarnagroup/GETL pull request #10
Opened 2020-09-08 13:45 UTC by ownbite

- Fix moto bug
- Add explode functionality to transform block

2020-09-08 13:50 UTC, ekstromchristian approved these changes

2020-09-08 18:02 UTC, bulv1ne commented
It seems there are other issues with moto 1.3.15, I suggest we fall back to version 1.3.14 (already done FYI) and resolve this when a new moto version is released. A patch version bump should not trigger so many problems for so many people 🤦

2020-09-08 19:01 UTC, bulv1ne requested changes
CHANGELOG.md not updated

2020-09-09 06:23 UTC, bulv1ne approved these changes

2020-09-09 06:23 UTC, merged